# Generated by Django 4.1.7 on 2023-03-06 02:56

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wahfimage",
            name="people",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Tag some people?",
                to="archives.person",
                verbose_name="People",
            ),
        ),
    ]
