# Generated by Django 4.1.7 on 2023-03-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0003_alter_wahfimage_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wahfimage",
            name="people",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tag some people?",
                to="archives.person",
                verbose_name="People",
            ),
        ),
    ]
