# Generated by Django 4.1.7 on 2023-03-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0004_alter_wahfimage_people"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wahfimage",
            name="location",
        ),
        migrations.AddField(
            model_name="wahfimage",
            name="locations",
            field=models.ManyToManyField(
                blank=True, to="archives.location", verbose_name="People"
            ),
        ),
        migrations.AlterField(
            model_name="wahfimage",
            name="people",
            field=models.ManyToManyField(
                blank=True, to="archives.person", verbose_name="People"
            ),
        ),
    ]
