# Generated by Django 4.1.7 on 2023-03-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0005_remove_wahfimage_location_wahfimage_locations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftTailNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AircraftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="wahfimage",
            name="locations",
            field=models.ManyToManyField(
                blank=True, to="archives.location", verbose_name="Locations"
            ),
        ),
        migrations.AddField(
            model_name="wahfimage",
            name="aircraft_registration",
            field=models.ManyToManyField(
                blank=True, to="archives.aircrafttailnumber", verbose_name="N Numbers"
            ),
        ),
        migrations.AddField(
            model_name="wahfimage",
            name="aircraft_type",
            field=models.ManyToManyField(
                blank=True, to="archives.aircrafttype", verbose_name="Aircraft Types"
            ),
        ),
    ]
