# Generated by Django 4.1.7 on 2023-03-11 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0006_aircrafttailnumber_aircrafttype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="name",
        ),
        migrations.AddField(
            model_name="person",
            name="name_search",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="person",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archives.wahfimage",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
