# Generated by Django 4.1.7 on 2023-03-14 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("archives", "0008_wahfcollectionlist_wahfcollectiongallery"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WAHFCollectionGallery",
            new_name="CollectionGallery",
        ),
        migrations.RenameModel(
            old_name="WAHFCollectionList",
            new_name="CollectionList",
        ),
    ]
