# Generated by Django 4.1.7 on 2023-03-14 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0010_collectiongallery_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collectiongallery",
            name="name",
        ),
    ]
