# Generated by Django 4.2.7 on 2023-11-29 15:05

import wagtail.images.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0011_remove_collectiongallery_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wahfrendition",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
    ]
