# Generated by Django 5.2.9 on 2025-12-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0012_alter_wahfrendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="wahfimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
    ]
