# Generated by Django 5.2.9 on 2025-12-09 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0013_wahfimage_description"),
        ("content", "0027_remove_inducteedetailpage_people_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wahfimage",
            name="aircraft_registration",
        ),
        migrations.RemoveField(
            model_name="wahfimage",
            name="aircraft_type",
        ),
        migrations.RemoveField(
            model_name="wahfimage",
            name="locations",
        ),
        migrations.RemoveField(
            model_name="person",
            name="image",
        ),
        migrations.RemoveField(
            model_name="wahfimage",
            name="people",
        ),
        migrations.DeleteModel(
            name="AircraftTailNumber",
        ),
        migrations.DeleteModel(
            name="AircraftType",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
