# Generated by Django 5.2.9 on 2026-01-02 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0016_alter_collectiongallery_og_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectiongallery",
            name="og_image_square",
            field=models.ForeignKey(
                blank=True,
                help_text="Square social media image (1080x1080 recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
        migrations.AddField(
            model_name="collectionlist",
            name="og_image_square",
            field=models.ForeignKey(
                blank=True,
                help_text="Square social media image (1080x1080 recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
    ]
