# Generated by Django 4.1.7 on 2023-03-12 14:53

import localflavor.us.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="business_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=localflavor.us.models.USStateField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="user",
            name="street_line1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="street_line2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="zip",
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
    ]
