# Generated by Django 4.1.7 on 2023-03-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_last_renewal_date_user_membership_expiry_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_renewal_date",
        ),
        migrations.AddField(
            model_name="user",
            name="renewal_payment_date",
            field=models.DateField(
                blank=True,
                help_text="The date they paid their membership dues.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="membership_expiry_date",
            field=models.DateField(
                blank=True,
                help_text="For WAHF - This is typically the last day of the year.",
                null=True,
            ),
        ),
    ]
