# Generated by Django 4.1.7 on 2023-03-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_street_line1_user_address_line1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership_automatic_payment",
            field=models.BooleanField(default=False),
        ),
    ]
