# Generated by Django 4.1.7 on 2023-03-18 19:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_membership_automatic_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipJoinSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("content", wagtail.fields.RichTextField()),
            ],
            options={
                "verbose_name_plural": "Membership Join Page - Top Copy",
            },
        ),
    ]
