# Generated by Django 4.1.7 on 2023-03-18 21:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_membershipjoinsnippet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membershipjoinsnippet",
            options={"verbose_name_plural": "Membership Join Page - Content Blocks"},
        ),
        migrations.AddField(
            model_name="membershipjoinsnippet",
            name="automatic_renewal_blurb",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="membershipjoinsnippet",
            name="credit_card_blurb",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="membershipjoinsnippet",
            name="lifetime_membership_blurb",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
