# Generated by Django 4.1.7 on 2023-03-19 22:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_user_stripe_customer_id_user_stripe_subscription_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MembershipJoinSnippet",
        ),
    ]
