# Generated by Django 4.1.7 on 2023-03-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_user_renewal_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="membership_automatic_payment",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
