# Generated by Django 4.1.7 on 2023-05-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_remove_user_address_line1_remove_user_address_line2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Email Address",
            ),
        ),
    ]
