# Generated by Django 4.2.7 on 2023-12-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_remove_member_membership_automatic_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="membership_renewal_reminder_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
