# Generated by Django 5.2.9 on 2025-12-23 05:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_member_membership_renewal_reminder_date"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="Member"),
            ],
            database_operations=[],
        ),
    ]
