version: "3.7"
services:
  db:
    image: postgres:15.2
    container_name: db
    environment:
      - POSTGRES_DB=wahf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    volumes:
      - ./.db/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: django
    env_file: .env
    command: python /app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      # - mailhog
    volumes:
      - .:/app
    ports:
      - 80:8000
      - 8000:8000
    stdin_open: true
    tty: true
  #mailhog:
  #  # image: mailhog/mailhog  # not arm
  #  image: anatomicjc/mailhog  # is arm64
  #  logging:
  #    driver: 'none'  # disable saving logs
  #  ports:
  #    - 1025:1025 # smtp server
  #    - 8025:8025 # web ui