# Generated by Django 4.1.7 on 2023-03-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershiplevel",
            name="price",
            field=models.PositiveSmallIntegerField(
                help_text="Annual price charged for this membership level."
            ),
        ),
    ]
