# Generated by Django 4.1.7 on 2023-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0003_membershiplevel_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiplevel",
            name="stripe_onetime_price_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="membershiplevel",
            name="stripe_recurring_price_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="membershiplevel",
            name="price",
            field=models.PositiveSmallIntegerField(
                help_text="Annual price charged for this membership level, in whole dollars (no cents). Example: 10"
            ),
        ),
    ]
