# Generated by Django 4.1.7 on 2023-03-19 22:21

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0004_membershiplevel_stripe_onetime_price_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipJoinSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("content", wagtail.fields.RichTextField()),
                ("lifetime_membership_blurb", wagtail.fields.RichTextField(blank=True)),
                ("credit_card_blurb", models.TextField(blank=True)),
                ("automatic_renewal_blurb", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Membership Join Page - Content Blocks",
            },
        ),
        migrations.CreateModel(
            name="MembershipThanksSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("content", wagtail.fields.RichTextField()),
            ],
            options={
                "verbose_name_plural": "Membership Thanks Page - Content Blocks",
            },
        ),
    ]
