# Generated by Django 4.1.7 on 2023-03-20 02:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0005_membershipjoinsnippet_membershipthankssnippet"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="membershiplevel",
            name="stripe_onetime_price_id",
        ),
        migrations.AddField(
            model_name="membershiplevel",
            name="allow_recurring_payments",
            field=models.BooleanField(default=False),
        ),
    ]
