# Generated by Django 4.1.7 on 2023-05-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0008_alter_membershipregistration_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiplevel",
            name="includes_spouse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membershiplevel",
            name="is_business",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="membershiplevel",
            name="is_lifetime",
            field=models.BooleanField(default=False),
        ),
    ]
