# Generated by Django 4.1.7 on 2023-05-23 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_member_membership_join_date"),
        ("membership", "0009_membershiplevel_includes_spouse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipregistration",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.member",
            ),
        ),
    ]
