# Generated by Django 4.1.7 on 2023-08-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0013_banquetrsvppage_banquetrsvpthankspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="BanquetPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_id", models.CharField(max_length=100)),
                ("amount_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=200)),
                ("item", models.CharField(max_length=200)),
                ("quantity", models.PositiveIntegerField()),
                ("attendee_names", models.CharField(max_length=250)),
                ("docent_tour", models.CharField(max_length=250)),
                ("signup_date", models.DateTimeField()),
            ],
        ),
    ]
