# Generated by Django 4.2.7 on 2023-12-01 05:26

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0014_banquetpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipRenewThanksSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("content", wagtail.fields.RichTextField()),
            ],
            options={
                "verbose_name_plural": "Membership Renew Thanks Page - Content Blocks",
            },
        ),
    ]
