# Generated by Django 4.2.11 on 2025-08-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0015_membershiprenewthankssnippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banquetpayment",
            name="attendee_names",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="banquetpayment",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="banquetpayment",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
