# Generated by Django 5.2.9 on 2025-12-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0016_alter_banquetpayment_attendee_names_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiplevel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membershiplevel",
            name="price_display",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="membershiplevel",
            name="show_on_membership_page",
            field=models.BooleanField(default=True),
        ),
    ]
