# Generated by Django 5.2.9 on 2025-12-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0018_membershiplevel_membership_page_sequence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membershiplevel",
            options={"ordering": ["membership_page_sequence"]},
        ),
        migrations.AddField(
            model_name="membershiplevel",
            name="membersihp_page_icon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
