# Generated by Django 5.2.9 on 2025-12-21 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0019_alter_membershiplevel_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="membershiplevel",
            old_name="membersihp_page_icon",
            new_name="membership_page_icon",
        ),
    ]
