# Generated by Django 5.2.9 on 2025-12-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "membership",
            "0020_rename_membersihp_page_icon_membershiplevel_membership_page_icon",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipContributionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("slug", models.SlugField()),
                ("description", models.TextField()),
                ("link", models.CharField(max_length=250)),
            ],
        ),
    ]
