# Generated by Django 5.2.9 on 2025-12-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0021_membershipcontributiontype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membershipcontributiontype",
            options={"ordering": ["sequence"]},
        ),
        migrations.AddField(
            model_name="membershipcontributiontype",
            name="sequence",
            field=models.PositiveSmallIntegerField(default=99),
        ),
    ]
