# Generated by Django 5.2.9 on 2025-12-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0022_alter_membershipcontributiontype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipcontributiontype",
            name="link",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
