# Generated by Django 5.2.9 on 2025-12-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0023_alter_membershipcontributiontype_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiplevel",
            name="stripe_price_id_one_time",
            field=models.CharField(
                blank=True,
                help_text="One-time (non-automatic) price ID",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membershiplevel",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, help_text="Recurring payment ID", max_length=50, null=True
            ),
        ),
    ]
