# Generated by Django 5.2.9 on 2025-12-22 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0024_membershiplevel_stripe_price_id_one_time_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MembershipJoinSnippet",
        ),
    ]
