# Generated by Django 5.2.9 on 2025-12-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0025_delete_membershipjoinsnippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiplevel",
            name="membership_page_text_class",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
