# Generated by Django 5.2.9 on 2025-12-23 05:09

import uuid

import django.db.models.deletion
import localflavor.us.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0026_membershiplevel_membership_page_text_class"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Member",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "membership_join_date",
                            models.DateField(
                                blank=True,
                                help_text="The date they joined WAHF.",
                                null=True,
                            ),
                        ),
                        (
                            "last_payment_date",
                            models.DateField(
                                blank=True,
                                help_text="The date they last paid their membership dues.",
                                null=True,
                            ),
                        ),
                        (
                            "membership_expiry_date",
                            models.DateField(blank=True, null=True),
                        ),
                        (
                            "membership_renewal_reminder_date",
                            models.DateField(blank=True, null=True),
                        ),
                        (
                            "stripe_customer_id",
                            models.CharField(blank=True, max_length=50),
                        ),
                        (
                            "stripe_subscription_id",
                            models.CharField(blank=True, max_length=50),
                        ),
                        (
                            "stripe_subscription_active",
                            models.BooleanField(default=False),
                        ),
                        ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                        (
                            "email",
                            models.EmailField(
                                blank=True,
                                max_length=254,
                                null=True,
                                unique=True,
                                verbose_name="Email Address",
                            ),
                        ),
                        ("first_name", models.CharField(blank=True, max_length=150)),
                        ("last_name", models.CharField(blank=True, max_length=150)),
                        ("business_name", models.CharField(blank=True, max_length=200)),
                        ("spouse_name", models.CharField(blank=True, max_length=200)),
                        ("address_line1", models.CharField(blank=True, max_length=200)),
                        ("address_line2", models.CharField(blank=True, max_length=200)),
                        ("city", models.CharField(blank=True, max_length=200)),
                        (
                            "state",
                            localflavor.us.models.USStateField(
                                blank=True, max_length=2
                            ),
                        ),
                        (
                            "zip",
                            localflavor.us.models.USZipCodeField(
                                blank=True, max_length=10
                            ),
                        ),
                        ("phone", models.CharField(blank=True, max_length=100)),
                        (
                            "membership_level",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                to="membership.membershiplevel",
                            ),
                        ),
                        (
                            "user",
                            models.OneToOneField(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="member",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE users_member RENAME TO membership_member;"
                ),
            ],
        )
    ]
