# Generated by Django 5.2.9 on 2025-12-23 05:15

from django.db import migrations


def remove_non_superusers(apps, schema_editor):
    # Use apps.get_model to get the User model from the historical state
    # This is safer than importing the model directly
    User = apps.get_model("users", "User")

    # Filter and delete users who are not superusers
    User.objects.filter(is_superuser=False).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0027_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="user",
        ),
        migrations.RunPython(remove_non_superusers),
    ]
