# Generated by Django 5.2.9 on 2025-12-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0028_remove_member_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberSignupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signup_datetime", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(default=dict)),
            ],
        ),
    ]
