# Generated by Django 5.2.9 on 2025-12-24 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0016_alter_collectiongallery_og_image_and_more"),
        ("membership", "0030_banquetrsvppage_og_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banquetrsvppage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
        migrations.AlterField(
            model_name="banquetrsvpthankspage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
    ]
