version: "3.7"
services:
  wahf-db:
    image: postgres:15.2
    container_name: wahf-db
    environment:
      - POSTGRES_DB=wahf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data/
    expose:
      - 5432
  wahf-cache:
    image: redis:7.2.3
    container_name: wahf-cache
    restart: always
    volumes:
      - ./.redis:/data
    expose:
      - 6379
  wahf-django:
    user: "${USER_RUN}:${GROUP_RUN}"
    build:
      context: .
      dockerfile: ./deploy/Dockerfile-production
    container_name: wahf-django
    env_file: .env
    volumes:
      - ./static:/app/static
      - ./static-collected:/app/static-collected
      - ./media:/app/media
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true
    tty: true
volumes:
  pg-data: