FROM python:3.11-slim-buster

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    APP_HOME=/app

# Install system packages required by Wagtail and Django.
RUN apt-get update --yes --quiet && apt-get install --yes --quiet --no-install-recommends \
    git \
    build-essential \
    libpq-dev \
    libmariadbclient-dev \
    libjpeg62-turbo-dev \
    zlib1g-dev \
    libwebp-dev \
 && rm -rf /var/lib/apt/lists/*

 # Use /app folder as a directory where the source code is stored.
WORKDIR $APP_HOME

# Install the project requirements.
COPY . .
COPY deploy/requirements/production.txt /
RUN pip install --no-cache-dir -r /production.txt


# RUN python manage.py collectstatic --noinput --clear

CMD set -xe; gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 30 --log-level debug wahf.wsgi:application
