FROM python:3.14-slim-bookworm

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    APP_HOME=/app

# Install system packages required by Wagtail and Django.
RUN apt-get update --yes --quiet && apt-get install --yes --quiet --no-install-recommends \
    build-essential \
    libpq-dev \
    libmariadb-dev \
    libjpeg62-turbo-dev \
    zlib1g-dev \
    libwebp-dev \
    git \
    poppler-utils \
 && rm -rf /var/lib/apt/lists/*


# Install the project requirements.
COPY deploy/requirements/*.txt /
RUN pip install -r /development.txt

# Use /app folder as a directory where the source code is stored.
WORKDIR $APP_HOME

CMD set -xe; python manage.py runserver 0.0.0.0:$PORT