# Generated by Django 4.1.7 on 2023-11-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecarditem",
            name="badge_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
