# Generated by Django 5.2.9 on 2026-01-02 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0017_collectiongallery_og_image_square_and_more"),
        ("home", "0004_alter_homepage_og_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="og_image_square",
            field=models.ForeignKey(
                blank=True,
                help_text="Square social media image (1080x1080 recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
    ]
