# Generated by Django 4.1.7 on 2023-03-11 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0007_remove_person_name_person_name_search_and_more"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InducteePhotoPlaceholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Placeholder image for inductees that are missing an image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="archives.wahfimage",
                    ),
                ),
            ],
        ),
    ]
