# Generated by Django 4.1.7 on 2023-03-05 05:23

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="wahfimage",
            name="uploaded_by_user",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploaded by user",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="content.wahfimage",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="link_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="content.menu",
            ),
        ),
        migrations.AddField(
            model_name="inducteedetailpage",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="content.person"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wahfrendition",
            unique_together={("image", "filter_spec", "focal_point_key")},
        ),
    ]
