# Generated by Django 4.1.7 on 2023-03-11 05:52

import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_inducteephotoplaceholder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inducteephotoplaceholder",
            options={
                "verbose_name_plural": "Inductees List - Missing Photo Placeholder Image"
            },
        ),
        migrations.AddField(
            model_name="inducteedetailpage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock())],
                default=[],
                use_json_field=True,
            ),
        ),
    ]
