# Generated by Django 4.1.7 on 2023-04-29 22:30

import django.db.models.deletion
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    InducteeDetailPage = apps.get_model("content", "InducteeDetailPage")
    db_alias = schema_editor.connection.alias

    for page in InducteeDetailPage.objects.using(db_alias).all():
        if page.person:
            page.people.add(page.person)

            page.name = f"{page.person.first_name} {page.person.last_name}"
            page.photo = page.person.image
            page.save()


def reverse_func(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0011_remove_collectiongallery_name"),
        ("content", "0004_articlelistpage_articlepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="inducteedetailpage",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="If multiple people are set above, you can customize thei name that is displayed here.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inducteedetailpage",
            name="people",
            field=models.ManyToManyField(
                related_name="inductee_people", to="archives.person"
            ),
        ),
        migrations.AddField(
            model_name="inducteedetailpage",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                help_text="Main image for the inductee list and primary photo for their page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archives.wahfimage",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
