# Generated by Django 4.1.7 on 2023-05-15 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0011_remove_collectiongallery_name"),
        ("content", "0005_inducteedetailpage_name_inducteedetailpage_people_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inducteedetailpage",
            name="person",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="archives.person",
            ),
        ),
    ]
