# Generated by Django 4.1.7 on 2023-05-20 16:09

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0011_remove_collectiongallery_name"),
        ("content", "0006_alter_inducteedetailpage_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inducteedetailpage",
            name="people",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="inductee_people", to="archives.person"
            ),
        ),
    ]
