# Generated by Django 4.1.7 on 2023-05-20 21:05

import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_alter_inducteedetailpage_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inducteedetailpage",
            name="gallery",
            field=wagtail.fields.StreamField(
                [("image", wagtail.images.blocks.ImageChooserBlock())],
                blank=True,
                default=[],
                use_json_field=True,
            ),
        ),
    ]
