# Generated by Django 4.1.7 on 2023-10-14 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_alter_scholarshiprecipient_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarshippage",
            name="bottom_images",
        ),
        migrations.RemoveField(
            model_name="scholarshippage",
            name="top_images",
        ),
    ]
