# Generated by Django 4.2.8 on 2024-11-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0015_kohnprojectpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kohnprojectpage",
            name="funding_dollars_raised",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="kohnprojectpage",
            name="funding_goal",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
