# Generated by Django 4.2.8 on 2024-11-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0016_alter_kohnprojectpage_funding_dollars_raised_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kohnprojectpage",
            name="show_donors_list",
            field=models.BooleanField(default=False),
        ),
    ]
