# Generated by Django 4.2.8 on 2024-11-02 04:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0017_kohnprojectpage_show_donors_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kohnprojectpage",
            name="funding_dollars_raised",
        ),
        migrations.RemoveField(
            model_name="kohnprojectpage",
            name="funding_goal",
        ),
        migrations.AddField(
            model_name="kohnprojectpage",
            name="fundraising_status",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="The description of the fundraising status of our project.",
            ),
        ),
    ]
