# Generated by Django 4.2.8 on 2024-11-05 05:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0018_remove_kohnprojectpage_funding_dollars_raised_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kohnprojectpage",
            name="silent_auction_donors",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="A list of individuals that donated items to the silent auction.",
            ),
        ),
        migrations.AddField(
            model_name="kohnprojectpage",
            name="special_donors",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="A list of special donors to be featured at the top of the page.",
            ),
        ),
    ]
