# Generated by Django 4.2.8 on 2025-07-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0019_kohnprojectpage_silent_auction_donors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="page_css",
            field=models.TextField(
                blank=True,
                help_text="Leave blank if you don't know what CSS is. This is custom styling for this article.",
                verbose_name="CSS/Style",
            ),
        ),
    ]
