# Generated by Django 4.2.11 on 2025-11-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0020_articlepage_page_css"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="top_badge",
            field=models.TextField(
                blank=True,
                help_text="A short tag placed over the image. Example 'WAHF: 40 YEARS, 40 STORIES",
                null=True,
            ),
        ),
    ]
