# Generated by Django 4.2.11 on 2025-11-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0021_articlepage_top_badge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="page_css",
            field=models.TextField(
                blank=True,
                help_text="Leave blank if you do not have any custom CSS. This is custom styling for this article.",
                verbose_name="CSS/Style",
            ),
        ),
    ]
