# Generated by Django 4.2.11 on 2025-11-25 05:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0022_alter_articlepage_page_css"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articlepage",
            options={"ordering": ["-website_publish_date", "-pk"]},
        ),
        migrations.AddField(
            model_name="articlepage",
            name="website_publish_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                default=datetime.date.today,
                help_text="This date is used for sorting the articles on the website. It is not displayed on the website.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="The date this article was published somewhere. Only displayed on the website.",
                null=True,
            ),
        ),
    ]
