# Generated by Django 4.2.11 on 2025-11-25 16:43

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models

import wahf.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("archives", "0012_alter_wahfrendition_file"),
        ("content", "0023_alter_articlepage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FourtyYearsFourtyStoriesListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wahf.mixins.OpenGraphMixin, "wagtailcore.page"),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "blockquote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.blocks.TextBlock(
                                        label="Quote", required=True
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.CreateModel(
            name="FourtyYearsStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_number", models.PositiveSmallIntegerField(unique=True)),
                (
                    "short_title",
                    models.CharField(
                        help_text="Shorter version of the title for the 40th page.",
                        max_length=250,
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fourty_article",
                        to="content.articlepage",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Article Image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="archives.wahfimage",
                    ),
                ),
            ],
            options={
                "ordering": ["-article_number"],
            },
        ),
    ]
