# Generated by Django 4.2.11 on 2025-11-25 16:49

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0024_fourtyyearsfourtystorieslistpage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fourtyyearsfourtystorieslistpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
