# Generated by Django 5.2.9 on 2025-12-09 03:19

from django.db import migrations, models


def set_first_last_names(apps, schema_editor):
    InducteeDetailPage = apps.get_model("content", "InducteeDetailPage")
    for page in InducteeDetailPage.objects.select_related("person"):
        if page.person:
            page.first_name = page.person.first_name
            page.last_name = page.person.last_name
            page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0025_fourtyyearsfourtystorieslistpage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inducteedetailpage",
            options={"ordering": ["last_name", "first_name", "name"]},
        ),
        migrations.AddField(
            model_name="inducteedetailpage",
            name="first_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Used for sorting on the Inductee List page.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inducteedetailpage",
            name="last_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Used for sorting on the Inductee List page.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inducteedetailpage",
            name="name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="First and Last Name, or a custom name if they are multiple people.",
                max_length=255,
                null=True,
                verbose_name="Display Name",
            ),
        ),
        migrations.RunPython(set_first_last_names),
    ]
