# Generated by Django 5.2.9 on 2025-12-09 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0026_alter_inducteedetailpage_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inducteedetailpage",
            name="people",
        ),
        migrations.RemoveField(
            model_name="inducteedetailpage",
            name="person",
        ),
    ]
