# Generated by Django 5.2.9 on 2025-12-09 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0027_remove_inducteedetailpage_people_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fourtyyearsstory",
            options={
                "ordering": ["-article_number"],
                "verbose_name_plural": "40/40 Stories",
            },
        ),
    ]
