# Generated by Django 5.2.9 on 2025-12-09 22:51

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0030_locationtag_inducteedetailpage_locations"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="inducteedetailpage",
            name="locations",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="I think we just want this to be a city name for now. Example: 'Milwaukee', 'Waukesha', etc.",
                through="content.LocationTag",
                to="taggit.Tag",
                verbose_name="Locations",
            ),
        ),
    ]
