# Generated by Django 5.2.9 on 2025-12-15 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0031_alter_inducteedetailpage_locations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inducteedetailpage",
            name="locations",
        ),
        migrations.DeleteModel(
            name="LocationTag",
        ),
    ]
