# Generated by Django 5.2.9 on 2025-12-15 03:11

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0032_remove_inducteedetailpage_locations_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        help_text="User-friendly name for the location (e.g., 'Eiffel Tower')",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="WGS 84 Latitude (-90 to +90)",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="WGS 84 Longitude (-180 to +180)",
                        max_digits=9,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Tag",
                "verbose_name_plural": "Location Tags",
            },
        ),
        migrations.CreateModel(
            name="TaggedLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_tag_page",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_locations",
                        to="content.locationtag",
                    ),
                ),
            ],
            options={
                "unique_together": {("tag", "content_object")},
            },
        ),
        migrations.AddField(
            model_name="inducteedetailpage",
            name="locations",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                help_text="A comma-separated list of tags.",
                through="content.TaggedLocation",
                to="content.LocationTag",
                verbose_name="Locations",
            ),
        ),
    ]
