# Generated by Django 5.2.9 on 2025-12-15 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0033_locationtag_taggedlocation_and_more"),
        ("wagtaildocs", "0014_alter_document_file_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentDownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "download_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Download Date"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "browser_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Browser/OS"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="wagtaildocs.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Download Log",
                "verbose_name_plural": "Document Download Logs",
            },
        ),
    ]
