# Generated by Django 5.2.9 on 2025-12-15 04:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0034_documentdownloadlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionalMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("year", models.PositiveSmallIntegerField(db_index=True)),
                ("attribution", models.TextField(blank=True)),
                ("attribution_link", models.TextField(blank=True)),
                ("tiles_url", models.CharField(blank=True, max_length=255, null=True)),
                ("min_zoom", models.PositiveSmallIntegerField(default=1)),
                ("max_zoom", models.PositiveSmallIntegerField(default=12)),
            ],
            options={
                "verbose_name_plural": "Sectional Map Tile Configs",
            },
        ),
        migrations.AlterField(
            model_name="taggedlocation",
            name="content_object",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_tag_page",
                to="content.inducteedetailpage",
            ),
        ),
    ]
