# Generated by Django 5.2.9 on 2025-12-21 20:44

import modelcluster.contrib.taggit
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0035_sectionalmap_alter_taggedlocation_content_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inducteedetailpage",
            name="locations",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="content.TaggedLocation",
                to="content.LocationTag",
                verbose_name="Locations",
            ),
        ),
    ]
