# Generated by Django 5.2.9 on 2025-12-24 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0036_alter_inducteedetailpage_locations"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlelistpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="articlepage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="fourtyyearsfourtystorieslistpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="freeformpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="inducteedetailpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="inducteelistpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="scholarshippage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
