# Generated by Django 5.2.9 on 2025-12-24 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0016_alter_collectiongallery_og_image_and_more"),
        ("content", "0037_articlelistpage_og_image_articlepage_og_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlelistpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
        migrations.AlterField(
            model_name="fourtyyearsfourtystorieslistpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
        migrations.AlterField(
            model_name="freeformpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
        migrations.AlterField(
            model_name="inducteedetailpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
        migrations.AlterField(
            model_name="inducteelistpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshippage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Social media image (1200x630px recommended)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archives.wahfimage",
            ),
        ),
    ]
