# Generated by Django 5.2.9 on 2025-12-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0038_alter_articlelistpage_og_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="menu_icon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
