# Generated by Django 5.2.9 on 2025-12-28 15:40

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0040_relatedarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="subtitle",
            field=models.TextField(
                blank=True,
                help_text="Text that appears under the title. Optional.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("image", 2),
                    ("blockquote", 4),
                    ("editorsnote", 6),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Quote", "required": True},
                    ),
                    4: ("wagtail.blocks.StructBlock", [[("quote", 3)]], {}),
                    5: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Editor's Note", "required": True},
                    ),
                    6: ("wagtail.blocks.StructBlock", [[("note", 5)]], {}),
                },
            ),
        ),
    ]
