# Generated by Django 4.1.7 on 2023-03-06 02:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

import wahf.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("archives", "0001_initial"),
        ("wagtaildocs", "0012_uploadeddocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagazineListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wahf.mixins.OpenGraphMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="MagazineIssuePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date of issue for this magazine release. Used for sorting issues by date."
                    ),
                ),
                (
                    "headline",
                    models.TextField(
                        help_text="Headline on the cover of the magazine."
                    ),
                ),
                (
                    "blurb",
                    wagtail.fields.RichTextField(
                        help_text="Short snippet of text describing the content inside this issue."
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        help_text="Cover image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="archives.wahfimage",
                    ),
                ),
                (
                    "download_pdf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
            bases=(wahf.mixins.OpenGraphMixin, "wagtailcore.page"),
        ),
    ]
