# Generated by Django 4.1.7 on 2023-07-15 04:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0002_magazineissuepage_issue_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MagazinePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.PositiveIntegerField(db_index=True)),
                ("text", models.TextField(blank=True)),
                ("guid", models.UUIDField(default=uuid.uuid4)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="magazine.magazineissuepage",
                    ),
                ),
            ],
            options={
                "ordering": ["page"],
            },
        ),
        migrations.AddConstraint(
            model_name="magazinepage",
            constraint=models.UniqueConstraint(
                fields=("issue", "page"), name="issuepageuniquetogether"
            ),
        ),
    ]
